// Valid Expo Router paths for CookVerse (SDK 54)
export const ROUTES = {
  root: "/",
  splash: "/splash",
  welcome: "/welcome",
  signIn: "/sign-in",
  signUp: "/sign-up",
  forgotPassword: "/forgot-password",
  createProfile: "/create-profile",
  tabs: "/(tabs)",
  home: "/(tabs)",
  search: "/search",
  generate: "/generate",
  upload: "/upload",
  profile: "/profile",
  settings: "/settings",
  followList: "/follow-list",
  about: "/about",
  privacy: "/privacy-policy",
  terms: "/terms-of-service",
  editRecipe: (id) => `/edit-recipe/${id}`,
  categories: "/categories",
  recipe: (id) => `/recipe/${id}?source=cookverse`,
};
